/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker/worker-env.d.ts` (hash: da1c151c912bf5d4007ea2bf2f3e3e06)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	GAME: DurableObjectNamespace<import("./index").GameDO>;
	USER: DurableObjectNamespace<import("./index").UserDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GameDO" | "UserDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
