/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker/worker-env.d.ts` (hash: a46667e4f1fe323c8c75118b5cb5fabd)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	GOOGLE_CLIENT_ID: "908007056119-hvrj0p5sa9k3rtcsbecqs7ehmf9rc82j.apps.googleusercontent.com";
	GAME: DurableObjectNamespace<import("./index").GameDO>;
	USER: DurableObjectNamespace<import("./index").UserDO>;
	SURVEY: DurableObjectNamespace<import("./index").SurveyDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GameDO" | "UserDO" | "SurveyDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
